# Generated by Django 4.0.6 on 2022-08-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Resto', '0005_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franquicia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('zona', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Franquicia',
                'verbose_name_plural': 'Franquicias',
            },
        ),
    ]
