# Generated by Django 4.0.6 on 2022-08-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Resto', '0006_franquicia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'List of Pasta',
                'verbose_name_plural': 'List of Pasta',
            },
        ),
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_choice', models.CharField(max_length=200)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category_description', models.TextField()),
            ],
            options={
                'verbose_name': 'List of Regular Pizza',
                'verbose_name_plural': 'List of Regular Pizza',
            },
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_choice', models.CharField(max_length=200)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category_description', models.TextField()),
            ],
            options={
                'verbose_name': 'List of Sicilian Pizza',
                'verbose_name_plural': 'List of Sicilian Pizza',
            },
        ),
    ]
