# Generated by Django 4.0.6 on 2022-08-18 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Resto', '0007_pasta_regularpizza_sicilianpizza'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pasta',
            new_name='Platos',
        ),
        migrations.DeleteModel(
            name='RegularPizza',
        ),
        migrations.DeleteModel(
            name='SicilianPizza',
        ),
        migrations.AlterModelOptions(
            name='platos',
            options={'verbose_name': 'List of Platos', 'verbose_name_plural': 'List of Platos'},
        ),
    ]
