# Generated by Django 4.0.6 on 2022-08-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Resto', '0010_userorder_alter_productos_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platos',
            new_name='Category',
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
