# Generated by Django 4.0.6 on 2022-08-19 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Resto', '0011_rename_platos_category_delete_userorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='imagen',
            new_name='category_gif',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='dish_name',
            new_name='category_title',
        ),
    ]
