# Generated by Django 4.0.6 on 2022-08-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Resto', '0012_rename_imagen_category_category_gif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_gif',
            field=models.ImageField(upload_to='static/assets/img'),
        ),
    ]
