# Generated by Django 4.0.6 on 2022-08-26 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Resto', '0014_alter_category_category_gif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Plato', 'verbose_name_plural': 'Platos'},
        ),
    ]
