# Generated by Django 4.0.6 on 2022-08-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Resto', '0016_reservas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscripcion',
        ),
        migrations.AlterModelOptions(
            name='reservas',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
