# Generated by Django 4.0.6 on 2022-09-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Resto', '0021_productos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
    ]
