# Generated by Django 4.0.6 on 2022-09-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Resto', '0022_alter_productos_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
