# Generated by Django 4.0.6 on 2022-09-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Resto', '0024_alter_reservas_dia_alter_reservas_horario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
